{% set name = "openorb" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/oorb/oorb/archive/refs/tags/v{{ version }}.zip
  sha256: 992a40b48eab5651f341fb411d5ad089001d638a8a8e3563319ece1dc8b95ef3
  patches:
    - 0001-conda-compat.patch # git diff master..conda > ../conda-forge/openorb-feedstock/recipe/conda-compat.patch
    - 0002-use-conda-gfortran.patch
    - 0003-use-conda-libgfortran.patch

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - make
    - {{ compiler('fortran') }}
  host:
    - python
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - openorb-data
    - openorb-data-de430

test:
  imports:
    - pyoorb
  source_files:
    - python/test.py
  commands:
    - python python/test.py

about:
  home: https://github.com/oorb/oorb
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: 'An open-source orbit-computation package'

  description: |
    OpenOrb (or OOrb) is an open-source orbit-computation package.
  doc_url: https://github.com/oorb/oorb/blob/master/README.md
  dev_url: https://github.com/oorb/oorb

extra:
  recipe-maintainers:
    - mjuric
    - bsipocz
    - rhiannonlynne
