{% set name = "openorb" %}
{% set version = "1.0.1.20191029" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/oorb/oorb.git
  git_rev: 475dc9db246bb3380e7d91f6e51fc3cb841f484a
  patches:
    - conda-compat.patch # git diff master..conda > ../conda-forge/openorb-feedstock/recipe/conda-compat.patch

build:
  number: 4
  skip: True  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - make
    - {{ compiler('fortran') }}
  host:
    - python
    - numpy
  run:
    - python
    - numpy
    - openorb-data
    - openorb-data-de430

test:
  imports:
    - pyoorb
  source_files:
    - python/test.py
  commands:
    - python python/test.py

about:
  home: https://github.com/oorb/oorb
  license: GPL-3.0
  license_family: GPL
  license_file: COPYING
  summary: 'An open-source orbit-computation package'

  description: |
    OpenOrb (or OOrb) is an open-source orbit-computation package.
  doc_url: https://github.com/oorb/oorb/blob/master/README.md
  dev_url: https://github.com/oorb/oorb

extra:
  recipe-maintainers:
    - mjuric
    - bsipocz
    - rhiannonlynne
