{% set name = "openorb" %}
{% set version = "1.0.1.20190122" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/oorb/oorb.git
  git_rev: 9fbf5686f325e276d658829d5a4fc518f8698c49
  patches:
    - conda-compat.patch # git diff master..conda > ../staged-recipes/recipes/openorb/conda-compat.patch

build:
  number: 1
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('fortran') }}
  host:
    - python
    - numpy
  run:
    - python
    - numpy
    - openorb-data
    - openorb-data-de430

test:
  imports:
    - pyoorb
  source_files:
    - python/test.py
  commands:
    - python python/test.py

about:
  home: https://github.com/oorb/oorb
  license: GPL-3.0
  license_family: GPL
  license_file: COPYING
  summary: 'An open-source orbit-computation package'

  description: |
    OpenOrb (or OOrb) is an open-source orbit-computation package.
  doc_url: https://github.com/oorb/oorb/blob/master/README.md
  dev_url: https://github.com/oorb/oorb

extra:
  recipe-maintainers:
    - mjuric
    - bsipocz
    - rhiannonlynne
